services:
  menu:
    build: src/menu-service
    env_file:
      - src/menu-service/.env
    image: menu-service:local
    container_name: menu-service
    environment:
      DB_HOST: db
      DB_PORT: "5432"
      DB_USER: <TBD>
      DB_PASSWORD: <TBD>
      DB_NAME: foodtruck
    ports:
      - "3000:3000"
    depends_on:
      - db
    restart: unless-stopped

  order:
    build: src/order-service
    env_file:
      - src/order-service/.env
    image: order-service:local
    container_name: order-service
    environment:
      MENU_URL: http://menu:3000
      DB_HOST: db
      DB_PORT: "5432"
      DB_USER: <TBD>
      DB_PASSWORD: <TBD>
      DB_NAME: foodtruck
    ports:
      - "4000:4000"
    depends_on:
      - menu
      - db
    restart: unless-stopped

  db:
    image: postgres:18
    container_name: foodtruck-db
    environment:
      POSTGRES_USER: <TBD>
      POSTGRES_PASSWORD: <TBD>
      POSTGRES_DB: foodtruck
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql
      - ./db-init:/docker-entrypoint-initdb.d:ro
    restart: unless-stopped

volumes:
  pgdata: {}
