services:
  menu:
    build: ./foodtruck-menu
    image: foodtruck-menu:local
    container_name: foodtruck-menu
    environment:
      DB_HOST: db
      DB_PORT: "5432"
      DB_USER: food
      DB_PASSWORD: foodpw
      DB_NAME: foodtruck
    ports:
      - "3000:3000"
    depends_on:
      - db
    restart: unless-stopped

  order:
    build: ./order-service
    image: order-service:local
    container_name: order-service
    environment:
      MENU_URL: http://menu:3000
      DB_HOST: db
      DB_PORT: "5432"
      DB_USER: food
      DB_PASSWORD: foodpw
      DB_NAME: foodtruck
    ports:
      - "4000:4000"
    depends_on:
      - menu
      - db
    restart: unless-stopped

  db:
    image: postgres:18
    container_name: foodtruck-db
    environment:
      POSTGRES_USER: food
      POSTGRES_PASSWORD: foodpw
      POSTGRES_DB: foodtruck
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql
      - ./db-init:/docker-entrypoint-initdb.d:ro
    restart: unless-stopped

volumes:
  pgdata: {}
